// <auto-generated />
namespace LeduInfo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addtblforvote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtblforvote));
        
        string IMigrationMetadata.Id
        {
            get { return "201212180746157_addtblforvote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
