// <auto-generated />
namespace LeduInfo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changeNum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeNum));
        
        string IMigrationMetadata.Id
        {
            get { return "201211280323464_changeNum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
