// <auto-generated />
namespace LeduInfo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201211281518372_addrelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
